# Catppuccin Mocha
[status]
separator_open  = "["
separator_close = "]"
separator_style = { fg = "#6c7086" }

[manager]
cwd = { fg = "#89b4fa" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#94e2d5" },
	{ mime = "video/*", fg = "#fab387" },
	{ mime = "audio/*", fg = "#cba6f7" },
	{ mime = "application/zip", fg = "#f9e2af" },
	{ mime = "application/gzip", fg = "#f9e2af" },
	{ mime = "application/x-tar", fg = "#f9e2af" },
]
