# Stylix dynamic — placeholders replaced by home.nix
[status]
separator_open  = "["
separator_close = "]"
separator_style = { fg = "{{base03}}" }

[manager]
cwd = { fg = "{{base0D}}" }

[filetype]
rules = [
	{ mime = "image/*", fg = "{{base0C}}" },
	{ mime = "video/*", fg = "{{base09}}" },
	{ mime = "audio/*", fg = "{{base0E}}" },
	{ mime = "application/zip", fg = "{{base0A}}" },
	{ mime = "application/gzip", fg = "{{base0A}}" },
	{ mime = "application/x-tar", fg = "{{base0A}}" },
]
