#!/bin/sh

nmcli device wifi hotspot ifname wlo1 ssid NixOS password henlo69420

iptables -I INPUT -i wlo1 -p udp --dport 67 -j ACCEPT
iptables -I INPUT -i wlo1 -p udp --dport 53 -j ACCEPT
iptables -I INPUT -i wlo1 -p tcp --dport 53 -j ACCEPT
