# Catppuccin Mocha
font_family      JuliaMono
font_size        12
foreground       #cdd6f4
background       #1e1e2e
background_opacity 0.67
selection_foreground #1e1e2e
selection_background #f5e0dc

# black
color0 #45475a
color8 #6c7086
# red
color1 #f38ba8
color9 #f2cdcd
# green
color2 #a6e3a1
color10 #a6e3a1
# yellow
color3 #f9e2af
color11 #fab387
# blue
color4 #89b4fa
color12 #74c7ec
# magenta
color5 #cba6f7
color13 #f5c2e7
# cyan
color6 #94e2d5
color14 #89dceb
# white
color7 #cdd6f4
color15 #b4befe

# ── Cursor ────────────────────────────────────────────────────────────────
cursor_shape     underline
cursor_blink_interval 0.5
cursor            #cdd6f4

# ── Scrolling ─────────────────────────────────────────────────────────────
scrollback_lines 10000

# ── Bell ──────────────────────────────────────────────────────────────────
enable_audio_bell no

# ── Performance ───────────────────────────────────────────────────────────
repaint_delay    6

# ── Window ────────────────────────────────────────────────────────────────
confirm_os_window_close 0
window_padding_width 0
window_margin_width  0
